{
  "openapi": "3.1.0",
  "info": {
    "description": "API documentation for Mojito backend",
    "title": "Mojito API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080/api/v1"
    }
  ],
  "paths": {
    "/items": {
      "get": {
        "description": "",
        "parameters": [
          {
            "in": "query",
            "name": "skip",
            "required": false,
            "schema": {
              "default": "0",
              "type": "integer"
            }
          },
          {
            "in": "query",
            "name": "limit",
            "required": false,
            "schema": {
              "default": "10",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "items": []
                  },
                  "properties": {
                    "items": {
                      "items": {
                        "properties": {
                          "created_at": {
                            "format": "date-time",
                            "type": "string"
                          },
                          "description": {
                            "type": "string"
                          },
                          "id": {
                            "items": {
                              "type": "integer"
                            },
                            "type": "array"
                          },
                          "title": {
                            "type": "string"
                          },
                          "updated_at": {
                            "format": "date-time",
                            "type": "string"
                          }
                        },
                        "type": "object"
                      },
                      "type": "array"
                    },
                    "meta": {
                      "properties": {
                        "limit": {
                          "type": "integer"
                        },
                        "skip": {
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "items"
        ]
      },
      "post": {
        "description": "Update handlers to use the new response types\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "description": "example",
                  "title": "example"
                },
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  }
                },
                "required": [
                  "title",
                  "description"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "description": "example",
                    "title": "example"
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "title": {
                      "type": "string"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "items"
        ]
      }
    },
    "/items/{id}": {
      "delete": {
        "description": "",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "message": "example"
                  },
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "items"
        ]
      },
      "get": {
        "description": "",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "description": "example",
                    "title": "example"
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "title": {
                      "type": "string"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "items"
        ]
      },
      "patch": {
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "description": "example",
                  "title": "example"
                },
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "title": {
                    "type": "string"
                  }
                },
                "required": [
                  "title",
                  "description"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "description": "example",
                    "title": "example"
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "title": {
                      "type": "string"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "items"
        ]
      }
    },
    "/login/access-token": {
      "post": {
        "description": "Login handlers with updated signatures\n",
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "example": {
                  "client_id": "example",
                  "client_secret": "example",
                  "grant_type": "example",
                  "password": "password123",
                  "scope": "example",
                  "username": "John Doe"
                },
                "properties": {},
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "access_token": "example",
                    "token_type": "example"
                  },
                  "properties": {
                    "access_token": {
                      "type": "string"
                    },
                    "token_type": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "login"
        ]
      }
    },
    "/login/test-token": {
      "get": {
        "description": "Update handler signatures to use pointer returns\n",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "user_id": "example"
                  },
                  "properties": {
                    "email": {
                      "type": "string"
                    },
                    "user_id": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "login"
        ]
      }
    },
    "/password-recovery-html-content/{email}": {
      "post": {
        "description": "@summary Get password recovery HTML content\n@tag login\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "html_content": "example"
                  },
                  "properties": {
                    "html_content": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "Get password recovery HTML content",
        "tags": [
          "login"
        ]
      }
    },
    "/password-recovery/{email}": {
      "post": {
        "description": "@summary Recover password\n@tag login\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "message": "example"
                  },
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "Recover password",
        "tags": [
          "login"
        ]
      }
    },
    "/reset-password": {
      "post": {
        "description": "@summary Reset password\n@tag login\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "password": "password123",
                  "token": "example"
                },
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "token": {
                    "type": "string"
                  }
                },
                "required": [
                  "token",
                  "password"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "message": "example"
                  },
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "Reset password",
        "tags": [
          "login"
        ]
      }
    },
    "/users": {
      "get": {
        "description": "Update listUsersHandler response\n",
        "parameters": [
          {
            "example": 123,
            "in": "query",
            "name": "skip",
            "required": false,
            "schema": {
              "default": "0",
              "type": "integer"
            }
          },
          {
            "example": 123,
            "in": "query",
            "name": "limit",
            "required": false,
            "schema": {
              "default": "10",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "users": []
                  },
                  "properties": {
                    "meta": {
                      "properties": {
                        "limit": {
                          "type": "integer"
                        },
                        "skip": {
                          "type": "integer"
                        }
                      },
                      "type": "object"
                    },
                    "users": {
                      "items": {
                        "properties": {
                          "created_at": {
                            "format": "date-time",
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "full_name": {
                            "type": "string"
                          },
                          "id": {
                            "items": {
                              "type": "integer"
                            },
                            "type": "array"
                          },
                          "is_active": {
                            "type": "boolean"
                          },
                          "is_superuser": {
                            "type": "boolean"
                          },
                          "updated_at": {
                            "format": "date-time",
                            "type": "string"
                          }
                        },
                        "type": "object"
                      },
                      "type": "array"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "users"
        ]
      }
    },
    "/users/me": {
      "delete": {
        "description": "Add new handlers\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "message": "example"
                  },
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Update getCurrentUserHandler response\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "full_name": "John Doe",
                    "is_active": true,
                    "is_superuser": true
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "is_superuser": {
                      "type": "boolean"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      },
      "patch": {
        "description": "Update response maps in other handlers to include phone_number\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "user@example.com",
                  "full_name": "John Doe"
                },
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "full_name": {
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "full_name": "John Doe",
                    "is_active": true,
                    "is_superuser": true
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "is_superuser": {
                      "type": "boolean"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      }
    },
    "/users/me/password": {
      "patch": {
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "current_password": "password123",
                  "new_password": "password123"
                },
                "properties": {
                  "current_password": {
                    "type": "string"
                  },
                  "new_password": {
                    "type": "string"
                  }
                },
                "required": [
                  "current_password",
                  "new_password"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "message": "example"
                  },
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      }
    },
    "/users/signup": {
      "post": {
        "description": "Update handler functions\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "email": "user@example.com",
                  "full_name": "John Doe",
                  "password": "password123"
                },
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "full_name": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "email",
                  "password",
                  "full_name"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "full_name": "John Doe",
                    "is_active": true,
                    "is_superuser": true
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "is_superuser": {
                      "type": "boolean"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "users"
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "description": "Update getUserHandler response\n",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "full_name": "John Doe",
                    "is_active": true,
                    "is_superuser": true
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "is_superuser": {
                      "type": "boolean"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      },
      "patch": {
        "description": "Update updateUserHandler to handle phone number\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "object"
                  },
                  "full_name": {
                    "type": "object"
                  },
                  "is_active": {
                    "type": "object"
                  },
                  "is_superuser": {
                    "type": "object"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "email": "example",
                    "full_name": "John Doe",
                    "is_active": true,
                    "is_superuser": true
                  },
                  "properties": {
                    "created_at": {
                      "format": "date-time",
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "full_name": {
                      "type": "string"
                    },
                    "id": {
                      "items": {
                        "type": "integer"
                      },
                      "type": "array"
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "is_superuser": {
                      "type": "boolean"
                    },
                    "updated_at": {
                      "format": "date-time",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "security": [
          {
            "OAuth2PasswordBearer": []
          }
        ],
        "summary": "",
        "tags": [
          "users"
        ]
      }
    },
    "/utils/health-check": {
      "get": {
        "description": "healthCheckHandler returns the health check response\n",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "status": true
                  },
                  "properties": {
                    "status": {
                      "type": "boolean"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "Successful Response"
          },
          "422": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            },
            "description": "Validation Error"
          }
        },
        "summary": "",
        "tags": [
          "utils"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "CreateItemRequest": {
        "properties": {
          "description": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description"
        ],
        "type": "object"
      },
      "GetItemRequest": {
        "properties": {},
        "type": "object"
      },
      "GetUserRequest": {
        "properties": {},
        "type": "object"
      },
      "HTMLContentResponse": {
        "properties": {
          "html_content": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "HTTPValidationError": {
        "properties": {
          "error": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "HealthCheckResponse": {
        "properties": {
          "status": {
            "type": "boolean"
          }
        },
        "type": "object"
      },
      "ItemResponse": {
        "properties": {
          "created_at": {
            "format": "date-time",
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "id": {
            "items": {
              "type": "integer"
            },
            "type": "array"
          },
          "title": {
            "type": "string"
          },
          "updated_at": {
            "format": "date-time",
            "type": "string"
          }
        },
        "type": "object"
      },
      "ItemsResponse": {
        "properties": {
          "items": {
            "items": {
              "properties": {
                "created_at": {
                  "format": "date-time",
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "id": {
                  "items": {
                    "type": "integer"
                  },
                  "type": "array"
                },
                "title": {
                  "type": "string"
                },
                "updated_at": {
                  "format": "date-time",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          },
          "meta": {
            "properties": {
              "limit": {
                "type": "integer"
              },
              "skip": {
                "type": "integer"
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      },
      "ListItemsRequest": {
        "properties": {},
        "type": "object"
      },
      "ListUsersRequest": {
        "properties": {},
        "type": "object"
      },
      "LoginAccessTokenRequest": {
        "properties": {},
        "type": "object"
      },
      "MessageResponse": {
        "properties": {
          "message": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "RecoverPasswordHTMLContentRequest": {
        "properties": {},
        "type": "object"
      },
      "RecoverPasswordRequest": {
        "properties": {},
        "type": "object"
      },
      "RegisterUserRequest": {
        "properties": {
          "email": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": [
          "email",
          "password",
          "full_name"
        ],
        "type": "object"
      },
      "ResetPasswordRequest": {
        "properties": {
          "password": {
            "type": "string"
          },
          "token": {
            "type": "string"
          }
        },
        "required": [
          "token",
          "password"
        ],
        "type": "object"
      },
      "TestTokenRequest": {
        "properties": {},
        "type": "object"
      },
      "TestTokenResponse": {
        "properties": {
          "email": {
            "type": "string"
          },
          "user_id": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "TokenResponse": {
        "properties": {
          "access_token": {
            "type": "string"
          },
          "token_type": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "UpdateItemRequest": {
        "properties": {
          "description": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        },
        "required": [
          "title",
          "description"
        ],
        "type": "object"
      },
      "UpdatePasswordRequest": {
        "properties": {
          "current_password": {
            "type": "string"
          },
          "new_password": {
            "type": "string"
          }
        },
        "required": [
          "current_password",
          "new_password"
        ],
        "type": "object"
      },
      "UpdateUserMeRequest": {
        "properties": {
          "email": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "UpdateUserRequest": {
        "properties": {
          "email": {
            "type": "object"
          },
          "full_name": {
            "type": "object"
          },
          "is_active": {
            "type": "object"
          },
          "is_superuser": {
            "type": "object"
          }
        },
        "type": "object"
      },
      "UserResponse": {
        "properties": {
          "created_at": {
            "format": "date-time",
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "full_name": {
            "type": "string"
          },
          "id": {
            "items": {
              "type": "integer"
            },
            "type": "array"
          },
          "is_active": {
            "type": "boolean"
          },
          "is_superuser": {
            "type": "boolean"
          },
          "updated_at": {
            "format": "date-time",
            "type": "string"
          }
        },
        "type": "object"
      },
      "UsersResponse": {
        "properties": {
          "meta": {
            "properties": {
              "limit": {
                "type": "integer"
              },
              "skip": {
                "type": "integer"
              }
            },
            "type": "object"
          },
          "users": {
            "items": {
              "properties": {
                "created_at": {
                  "format": "date-time",
                  "type": "string"
                },
                "email": {
                  "type": "string"
                },
                "full_name": {
                  "type": "string"
                },
                "id": {
                  "items": {
                    "type": "integer"
                  },
                  "type": "array"
                },
                "is_active": {
                  "type": "boolean"
                },
                "is_superuser": {
                  "type": "boolean"
                },
                "updated_at": {
                  "format": "date-time",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          }
        },
        "type": "object"
      }
    },
    "securitySchemes": {
      "OAuth2PasswordBearer": {
        "flows": {
          "password": {
            "scopes": {},
            "tokenUrl": "/api/v1/login/access-token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}